Repository sparkbox/sparkeats, pull requests merged in 2022-10, with the labels that each got.

#412 feat: add page routes
  package.json
  src/App.tsx
  src/main.tsx
  yarn.lock
Labels: react-ts-rebuild

#411 feat: add and configure Stylelint
  .stylelintrc.json
  package.json
  src/App.scss
  src/scss/components/_buttons.scss
  src/scss/components/_footer.scss
  src/scss/components/_location-dropdown.scss
  src/scss/components/_place-card.scss
  src/scss/components/_review-header.scss
  src/scss/components/_review-nav.scss
  src/scss/components/_review-overview.scss
  src/scss/components/_review-submission.scss
  src/scss/components/_sparkeats-header.scss
  src/scss/generic/_normalize.scss
  src/scss/objects/_homepage.scss
  src/scss/objects/_review-page.scss
  src/scss/settings/_breakpoints.scss
  src/scss/settings/_colors.scss
  src/scss/settings/_fonts.scss
Labels: hacktoberfest-accepted, react-ts-rebuild

#397 Adding the templete for pr-request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#426 chore: add and configure typescript eslint
  .eslintrc.cjs
  package.json
  src/components/HomePage.tsx
  src/types/global.d.ts
  yarn.lock
Labels: hacktoberfest-accepted, react-ts-rebuild

#424 feat: SiteHeader has been rebuilt
  src/App.scss
  src/App.tsx
  src/components/SiteHeader.tsx
  src/scss/components/_site-header.scss
Labels: hacktoberfest-accepted, react-ts-rebuild

#427 Shyambh cypress
  .gitignore
  cypress.config.ts
  cypress/e2e/Home.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/components/SiteHeader.tsx
  tsconfig.json
  yarn.lock
Labels: hacktoberfest-accepted, react-ts-rebuild
